before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm
archives:
  -
    wrap_in_directory: true
    files:
      - extras/**/*
release:
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
