before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm
release:
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"
  extra_files:
    - glob: ./extras/**/*
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
